salesforce-team-back-market/salesforce-main-3

force-app/main/default/flows/Case_After_Save_Flow_SSC.flow-meta.xml

[DevOps Center] Merge WI-000033 to Integration

---

force-app/main/default/flows/Case_After_Save_Flow_SSC.flow-meta.xml

[DevOps Center] Merge WI-000033 to UAT

---

force-app/main/default/flows/Case_After_Save_Flow_SSC.flow-meta.xml

[DevOps Center] Merge WI-000033 to Staging

---

force-app/main/default/flows/Case_After_Save_Flow_SSC.flow-meta.xml

[DevOps Center] Merge Staging to Production

---

force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml
force-app/main/default/objects/Alert__c/fields/Objective_to_reach__c.field-meta.xml
force-app/main/default/objects/Alert__c/fields/Rate_Critical_threshold__c.field-meta.xml

Reverts salesforce-team-back-market/salesforce-main-3#8

Revert "[DevOps Center] Merge WI-000034 to Integration"

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml
force-app/main/default/flows/Schedule_flow_Alert_MP_LC_emails_and_limitation.flow-meta.xml

[DevOps Center] Merge WI-000036 to Integration

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml
force-app/main/default/flows/Schedule_flow_Alert_MP_LC_emails_and_limitation.flow-meta.xml

[DevOps Center] Merge WI-000036 to UAT

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml
force-app/main/default/flows/Schedule_flow_Alert_MP_LC_emails_and_limitation.flow-meta.xml

[DevOps Center] Merge WI-000036 to Staging

---

force-app/main/default/flexipages/Revamped_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000041 to Integration

---

force-app/main/default/flexipages/Revamped_Account_Record_Page.flexipage-meta.xml

[DevOps Center] Merge WI-000041 to UAT

---

force-app/main/default/flows/Performance_Data_Flow_After_Save_V1.flow-meta.xml
force-app/main/default/flows/Schedule_Flow_Early_Release_MP_process.flow-meta.xml
force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml
force-app/main/default/objects/Alert__c/fields/Cases_Objective_to_reach__c.field-meta.xml

[DevOps Center] Merge WI-000039 to Integration

---

force-app/main/default/flows/Performance_Data_Flow_After_Save_V1.flow-meta.xml
force-app/main/default/flows/Schedule_Flow_Early_Release_MP_process.flow-meta.xml
force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml
force-app/main/default/objects/Alert__c/fields/Cases_Objective_to_reach__c.field-meta.xml

[DevOps Center] Merge WI-000039 to UAT

---

force-app/main/default/flows/Performance_Data_Flow_After_Save_V1.flow-meta.xml
force-app/main/default/flows/Schedule_Flow_Early_Release_MP_process.flow-meta.xml
force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml
force-app/main/default/objects/Alert__c/fields/Cases_Objective_to_reach__c.field-meta.xml

[DevOps Center] Merge WI-000039 to Staging

---

force-app/main/default/flows/Schedule_Flow_NMO_Stage_email_automation.flow-meta.xml

[DevOps Center] Merge WI-000043 to Integration

---

force-app/main/default/flows/Schedule_Flow_NMO_Stage_email_automation.flow-meta.xml

[DevOps Center] Merge WI-000043 to UAT

---

force-app/main/default/flows/Schedule_Flow_NMO_Stage_email_automation.flow-meta.xml

[DevOps Center] Merge WI-000043 to Staging

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml
force-app/main/default/flows/Alert_After_save_flow_Creation_only.flow-meta.xml

[DevOps Center] Merge WI-000037 to Integration

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml
force-app/main/default/flows/Alert_After_save_flow_Creation_only.flow-meta.xml

[DevOps Center] Merge WI-000037 to UAT

---

force-app/main/default/flows/Case_Before_Update_Flow_Update_origin_skill_from_new_queue.flow-meta.xml

[DevOps Center] Merge WI-000045 to Integration

---

force-app/main/default/flows/Case_Before_Update_Flow_Update_origin_skill_from_new_queue.flow-meta.xml

[DevOps Center] Merge WI-000045 to UAT

---

force-app/main/default/flows/Case_Before_Update_Flow_Update_origin_skill_from_new_queue.flow-meta.xml

[DevOps Center] Merge WI-000045 to Staging

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls
force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls-meta.xml
force-app/main/default/classes/DeleteDuplicatedContactsSchedulable.cls
force-app/main/default/classes/DeleteDuplicatedContactsSchedulable.cls-meta.xml
force-app/main/default/classes/DeleteDuplicatedContactsTest.cls
force-app/main/default/classes/DeleteDuplicatedContactsTest.cls-meta.xml
force-app/main/default/classes/LogService.cls
force-app/main/default/classes/TestFactory.cls
force-app/main/default/flows/Schedule_Flow_Contact_deletion_flow.flow-meta.xml

[DevOps Center] Merge WI-000047 to Integration

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls
force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls-meta.xml
force-app/main/default/classes/DeleteDuplicatedContactsSchedulable.cls
force-app/main/default/classes/DeleteDuplicatedContactsSchedulable.cls-meta.xml
force-app/main/default/classes/DeleteDuplicatedContactsTest.cls
force-app/main/default/classes/DeleteDuplicatedContactsTest.cls-meta.xml
force-app/main/default/classes/LogService.cls
force-app/main/default/classes/TestFactory.cls
force-app/main/default/flows/Schedule_Flow_Contact_deletion_flow.flow-meta.xml

[DevOps Center] Merge WI-000047 to Staging

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls

[DevOps Center] Merge WI-000049 to Integration

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls

[DevOps Center] Merge WI-000049 to Staging

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls

[DevOps Center] Merge WI-000050 to Integration

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls

[DevOps Center] Merge WI-000050 to UAT

---

force-app/main/default/classes/DeleteDuplicatedContactsBatch.cls

[DevOps Center] Merge WI-000050 to Staging

---

force-app/main/default/flows/Schedule_Flow_Early_Release_MP_process.flow-meta.xml
force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml

[DevOps Center] Merge WI-000052 to Integration

---

force-app/main/default/flows/Schedule_Flow_Early_Release_MP_process.flow-meta.xml
force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml

[DevOps Center] Merge WI-000052 to UAT

---

force-app/main/default/flows/Schedule_Flow_Early_Release_MP_process.flow-meta.xml
force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml

[DevOps Center] Merge WI-000052 to Staging

---

force-app/main/default/flows/Case_Before_Save_Flow.flow-meta.xml

[DevOps Center] Merge WI-000057 to Integration

---

force-app/main/default/flows/Case_Before_Save_Flow.flow-meta.xml

[DevOps Center] Merge WI-000057 to UAT

---

force-app/main/default/flows/Case_Before_Save_Flow.flow-meta.xml

[DevOps Center] Merge WI-000057 to Staging

---

force-app/main/default/flows/Alert_email_to_list_of_contact.flow-meta.xml

[DevOps Center] Merge WI-000058 to Integration

---

force-app/main/default/flows/Alert_email_to_list_of_contact.flow-meta.xml

[DevOps Center] Merge WI-000058 to UAT

---

force-app/main/default/flows/Alert_email_to_list_of_contact.flow-meta.xml

[DevOps Center] Merge WI-000058 to Staging

---

force-app/main/default/flows/Screen_Flow_SSC_Case_v2.flow-meta.xml
force-app/main/default/globalValueSets/Challenging_points.globalValueSet-meta.xml
force-app/main/default/objects/Case/fields/Case_Reason_Details__c.field-meta.xml
force-app/main/default/objects/Case/recordTypes/Seller_Support_Case.recordType-meta.xml

[DevOps Center] Merge WI-000053 to UAT

---

force-app/main/default/flows/Screen_Flow_SSC_Case_v2.flow-meta.xml

[DevOps Center] Merge WI-000055 to UAT

---

force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml

[DevOps Center] Merge WI-000061 to Integration

---

force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml

[DevOps Center] Merge WI-000061 to UAT

---

force-app/main/default/flows/Scheduled_Flow_Update_Alert_stage_and_Critical_rate.flow-meta.xml

[DevOps Center] Merge WI-000061 to Staging

---

force-app/main/default/classes/DCE_Test_Trigger_Contact_Account.cls
force-app/main/default/classes/DCE_TriggersTest.cls
force-app/main/default/classes/TestFactory.cls

[DevOps Center] Merge WI-000064 to Integration

---

force-app/main/default/classes/DCE_Test_Trigger_Contact_Account.cls
force-app/main/default/classes/DCE_TriggersTest.cls
force-app/main/default/classes/TestFactory.cls

[DevOps Center] Merge WI-000064 to UAT

---

force-app/main/default/flows/Screen_Flow_SSC_Case_v2.flow-meta.xml

[DevOps Center] Merge WI-000055 to Staging

---

force-app/main/default/flows/Screen_Flow_SSC_Case_v2.flow-meta.xml
force-app/main/default/globalValueSets/Challenging_points.globalValueSet-meta.xml
force-app/main/default/objects/Case/fields/Case_Reason_Details__c.field-meta.xml
force-app/main/default/objects/Case/recordTypes/Seller_Support_Case.recordType-meta.xml

[DevOps Center] Merge WI-000053 to Staging

---

force-app/main/default/audience/Sellers_Sales_or_Buyback.audience-meta.xml

[DevOps Center] Merge WI-000066 to Integration

---

force-app/main/default/audience/Sellers_Sales_or_Buyback.audience-meta.xml

[DevOps Center] Merge WI-000066 to UAT

---

force-app/main/default/audience/Sellers_Sales_or_Buyback.audience-meta.xml

[DevOps Center] Merge WI-000066 to Staging

---

force-app/main/default/flows/Case_Before_save_flow_Assign_Owner_to_Close_User.flow-meta.xml

[DevOps Center] Merge WI-000068 to Integration

---

force-app/main/default/flows/Case_Before_save_flow_Assign_Owner_to_Close_User.flow-meta.xml

[DevOps Center] Merge WI-000068 to UAT

---

force-app/main/default/classes/AccountTriggerHandler.cls

[DevOps Center] Merge WI-000070 to Integration

---

force-app/main/default/classes/AccountTriggerHandler.cls

[DevOps Center] Merge WI-000070 to UAT

---

force-app/main/default/classes/AccountTriggerHandler.cls

[DevOps Center] Merge WI-000070 to Staging

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml

[DevOps Center] Merge WI-000069 to Integration

---

force-app/main/default/flows/Case_Before_save_flow_Assign_Owner_to_Close_User.flow-meta.xml

[DevOps Center] Merge WI-000068 to Staging

---

force-app/main/default/flows/Alert_After_Save_Flow_Update_Only.flow-meta.xml

[DevOps Center] Merge WI-000069 to Staging

---

force-app/main/default/flows/Merchant_Flow_After_Save.flow-meta.xml
force-app/main/default/flows/Merchant_Flow_After_Save_Update_targeted_countries_when_offline.flow-meta.xml

[DevOps Center] Merge WI-000075 to Integration

---

force-app/main/default/flows/Merchant_Flow_After_Save.flow-meta.xml
force-app/main/default/flows/Merchant_Flow_After_Save_Update_targeted_countries_when_offline.flow-meta.xml

[DevOps Center] Merge WI-000075 to UAT

---

force-app/main/default/flows/Case_Before_Save_Flow_SSC_Set_ownership_and_skills.flow-meta.xml

[DevOps Center] Merge WI-000076 to Integration
